apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: default
  labels:
    name: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: nginx:latest
          imagePullPolicy: Always
          ports:
            - name: http-server
              containerPort: 80
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

