apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduled-hpa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduled-hpa
rules:
  - apiGroups:
    - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
    - apps
    resources:
      - deployments
      - deployments/scale
    verbs:
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scheduled-hpa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scheduled-hpa
subjects:
  - kind: ServiceAccount
    name: scheduled-hpa
    namespace: default

